#!/usr/bin/env bash
#
# Writes the backend.hcl of a single stack, so every stack keeps its own Terraform state object.
#
# Sharing one -backend-config between stacks points them all at the same state key. The stack that
# runs second then loads the first stack's state, finds resources that are not in its own
# configuration and plans to destroy them. Generating the file per stack, with the state key as an
# explicit argument, makes that mistake impossible to make by accident.
#
# Usage: write-backend-config.sh <stack-directory> <state-key>
#
#   write-backend-config.sh terraform/stacks/platform platform/terraform.tfstate
#   write-backend-config.sh terraform/stacks/addons   addons/terraform.tfstate
#   write-backend-config.sh terraform/stacks/environment "environments/${ENVIRONMENT_NAME}/terraform.tfstate"
#
# Required environment: TF_STATE_BUCKET, TF_STATE_REGION, TF_STATE_ENDPOINT.
#
# Credentials are never written to the file. The S3 backend reads them from AWS_ACCESS_KEY_ID and
# AWS_SECRET_ACCESS_KEY, which in CI come from the TF_STATE_ACCESS_KEY and TF_STATE_SECRET_KEY
# repository secrets.

set -euo pipefail

STACK_DIR="${1:?usage: write-backend-config.sh <stack-directory> <state-key>}"
STATE_KEY="${2:?usage: write-backend-config.sh <stack-directory> <state-key>}"

: "${TF_STATE_BUCKET:?TF_STATE_BUCKET must be set}"
: "${TF_STATE_REGION:?TF_STATE_REGION must be set}"
: "${TF_STATE_ENDPOINT:?TF_STATE_ENDPOINT must be set}"

[ -d "$STACK_DIR" ] || { echo "No such stack directory: ${STACK_DIR}" >&2; exit 1; }

target="${STACK_DIR%/}/backend.hcl"

cat > "$target" <<HCL
# Generated by scripts/write-backend-config.sh. Do not edit by hand and do not share this file
# between stacks: the key below is what keeps this stack's state separate from the others.

bucket = "${TF_STATE_BUCKET}"
key    = "${STATE_KEY}"
region = "${TF_STATE_REGION}"

endpoints = {
  s3 = "${TF_STATE_ENDPOINT}"
}

# OVHcloud Object Storage requires path style addressing and does not implement the AWS account
# and metadata endpoints Terraform would otherwise probe.
use_path_style              = true
skip_credentials_validation = true
skip_region_validation      = true
skip_requesting_account_id  = true
skip_metadata_api_check     = true
skip_s3_checksum            = true

# State locking through a lock object next to the state file, so no DynamoDB table is needed.
use_lockfile = true
HCL

echo "Wrote ${target} (key ${STATE_KEY})"
